# Navigate to your repo
name: Deploy Infrastructure and Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

env:
  TF_VERSION: '1.5.0'
  PROJECT_ID: 'sevenl33-v2-25'
  BUCKET_NAME: 'resume-sevenl33-v2-25'

jobs:
  terraform-check:
    name: Terraform Plan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init
    
    - name: Terraform Format Check
      working-directory: ./terraform
      run: terraform fmt -check
      continue-on-error: true
    
    - name: Terraform Plan
      working-directory: ./terraform
      run: terraform plan -out=tfplan
    
    - name: Upload Plan
      uses: actions/upload-artifact@v3
      if: github.event_name == 'pull_request'
      with:
        name: tfplan
        path: terraform/tfplan

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: terraform-check
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init
    
    - name: Terraform Apply
      working-directory: ./terraform
      run: terraform apply -auto-approve

  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    needs: terraform-apply
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    
    - name: Deploy Frontend to Cloud Storage
      run: |
        gsutil -m rsync -r -d frontend/website gs://${{ env.BUCKET_NAME }}/

  deploy-function:
    name: Deploy Cloud Function
    runs-on: ubuntu-latest
    needs: terraform-apply
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{secrets.GCP_SA_KEY}}
    
    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    
    - name: Deploy Cloud Function
      working-directory: ./backend
      run: |
        gcloud functions deploy visitor-counter \
          --gen2 \
          --runtime python312 \
          --trigger-http \
          --allow-unauthenticated \
          --entry-point visitor_counter \
          --region us-central1 \
          --project ${{ env.PROJECT_ID }}
